FROM public.ecr.aws/lambda/nodejs:20

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY lib ./lib
COPY db ./db
COPY data ./data
COPY public ./public
COPY server.js ./

CMD ["server.handler"]
