// Seed data for a fresh database, generated once from data/certifications.xlsx
// + data/manual-entries.json. The parser that produced it (lib/parseWorkbook.js)
// has since been removed, so THIS FILE is now the source of truth — regenerating
// it would mean restoring that parser from git history.
//
// 144 certificates across 14 employees and 37 vendors.
// Two duplicate employee+vendor+certificate rows in the sheet were dropped.
//
// Emails follow firstname.lastname@mcsholding.com and are written out literally
// so they can be reviewed in a diff. A wrong address means that person cannot
// log in; correct it here before seeding, or via the admin update-profile action after.

const users = [
  { fullName: "Mahmoud Ahmed", email: "mahmoud.ahmed@mcsholding.com", department: null, role: "employee" },
  { fullName: "Mazen Mayhob", email: "mazen.mayhob@mcsholding.com", department: null, role: "employee" },
  { fullName: "Ali Mohamed", email: "ali.mohamed@mcsholding.com", department: null, role: "employee" },
  { fullName: "Mohamed Shafik", email: "mohamed.shafik@mcsholding.com", department: null, role: "employee" },
  { fullName: "Ahmed Elkhresy", email: "ahmed.elkhresy@mcsholding.com", department: null, role: "employee" },
  { fullName: "Ramy Mohamed", email: "ramy.mohamed@mcsholding.com", department: null, role: "employee" },
  { fullName: "Mahmoud Rayan", email: "mahmoud.rayan@mcsholding.com", department: null, role: "employee" },
  { fullName: "Omar Jamal", email: "omar.jamal@mcsholding.com", department: null, role: "employee" },
  { fullName: "Mostafa Samy", email: "mostafa.samy@mcsholding.com", department: null, role: "employee" },
  { fullName: "Mohamed Ghanem", email: "mohamed.ghanem@mcsholding.com", department: null, role: "employee" },
  { fullName: "Fares Abdeldaym", email: "fares.abdeldaym@mcsholding.com", department: null, role: "employee" },
  { fullName: "Ahmed Ibrahim", email: "ahmed.ibrahim@mcsholding.com", department: null, role: "employee" },
  { fullName: "Abdelrahman Musaa", email: "abdelrahman.musaa@mcsholding.com", department: null, role: "employee" },
  { fullName: "Omar Semeet", email: "omar.semeet@mcsholding.com", department: null, role: "employee" },
];

const certificates = [
  { employee: "Mahmoud Ahmed", vendor: "Palo Alto", certificate: "PSE Strata", expirationDate: "2026-10-31", expirationText: "2026-10-31", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Palo Alto", certificate: "PCNSE", expirationDate: "2026-04-25", expirationText: "2026-04-25", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "Application delivery 101", expirationDate: "2026-01-25", expirationText: "2026-01-25", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "Administrator 201", expirationDate: "2026-01-25", expirationText: "2026-01-25", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "ASM-303", expirationDate: "2026-06-25", expirationText: "2026-06-25", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "APM-304", expirationDate: "2026-08-25", expirationText: "2026-08-25", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Fortinet", certificate: "Professional Network Security", expirationDate: "2024-02-24", expirationText: "2024-02-24", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Fortinet", certificate: "Certified Associate Cybersecurity", expirationDate: "2024-10-24", expirationText: "2024-10-24", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Fortinet", certificate: "Fundamentals Cybersecurity", expirationDate: "2024-10-24", expirationText: "2024-10-24", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Kaspersky", certificate: "HybridCloud Security.Virtualization-Light Agent", expirationDate: null, expirationText: "Not Exp", kind: "no_expiration" },
  { employee: "Mahmoud Ahmed", vendor: "Kaspersky", certificate: "Kaspersky Security for Windows Server", expirationDate: null, expirationText: "Not Exp", kind: "no_expiration" },
  { employee: "Mahmoud Ahmed", vendor: "TCM", certificate: "Practical Ethical Hacking", expirationDate: null, expirationText: "Not Exp", kind: "no_expiration" },
  { employee: "Mahmoud Ahmed", vendor: "EfficientIP", certificate: "DDI Administrator V8", expirationDate: null, expirationText: "Not Exp", kind: "no_expiration" },
  { employee: "Mahmoud Ahmed", vendor: "Palo Alto", certificate: "NGFW-Engineer", expirationDate: "2027-10-08", expirationText: "2027-10-08", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "Palo Alto", certificate: "Netsec Pro", expirationDate: "2027-10-10", expirationText: "2027-10-10", kind: "date" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "BIG-IP LTM Specialist", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Ahmed", vendor: "f5", certificate: "Security Solutions", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mazen Mayhob", vendor: "Gigamon", certificate: "GigaTECH Certificate Test", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mazen Mayhob", vendor: "Gigamon", certificate: "Gigamon GigaPRO associate.", expirationDate: "2026-12-29", expirationText: "2026-12-29", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "Ivanti", certificate: "Ivanti Security Controls - Administrator", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mazen Mayhob", vendor: "Palo Alto", certificate: "EDU-210", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mazen Mayhob", vendor: "Palo Alto", certificate: "PCNSE", expirationDate: "2026-07-12", expirationText: "July 13, 2026", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "Tenable", certificate: "Tenable Security Center Specialist", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mazen Mayhob", vendor: "Tenable", certificate: "Partner Sales Associate-NESSUS", expirationDate: "2025-12-25", expirationText: "25-12-2025", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "Tenable", certificate: "Partner Sales Engineer Vulnerability Management", expirationDate: "2026-12-26", expirationText: "26-12-2026", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "Tenable", certificate: "Partner Sales Engineer - Identity Security", expirationDate: "2026-02-13", expirationText: "13-2-2026", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "f5", certificate: "Application delivery 101", expirationDate: "2027-04-27", expirationText: "27-4-2027", kind: "date" },
  { employee: "Mazen Mayhob", vendor: "NTI", certificate: "Operating systems Administration (OSA)", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mazen Mayhob", vendor: "f5", certificate: "TMOS Administration (201)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "IBM", certificate: "Qradar Security information and Event managemnet Foundation", expirationDate: "2025-06-30", expirationText: "2025-06-30", kind: "date" },
  { employee: "Ali Mohamed", vendor: "IBM", certificate: "SOAR Resilient Foundation", expirationDate: null, expirationText: "expired", kind: "expired_flag" },
  { employee: "Ali Mohamed", vendor: "IBM", certificate: "IBM Guardiam Foundation", expirationDate: null, expirationText: "expired", kind: "expired_flag" },
  { employee: "Ali Mohamed", vendor: "IBM", certificate: "Verify Privilege Technical intermediate", expirationDate: "2025-06-30", expirationText: "2025-06-30", kind: "date" },
  { employee: "Ali Mohamed", vendor: "Forcepoint", certificate: "web security On-Premises Administrator", expirationDate: null, expirationText: "no exp", kind: "no_expiration" },
  { employee: "Ali Mohamed", vendor: "Fortinet", certificate: "Certified Fundementals cybersecurity", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "IBM", certificate: "Qradar Administration badge", expirationDate: null, expirationText: "NO exp", kind: "no_expiration" },
  { employee: "Ali Mohamed", vendor: "Cisco", certificate: "CyberOps Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "Infoblox", certificate: "BloxOne ThreatDefence", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "Infoblox", certificate: "Qualified DNS Security Professional (DSP)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "Infoblox", certificate: "Universal DDI", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "Fortinet", certificate: "NSE 3 Network Security Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "NTI", certificate: "Cyber Operation Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ali Mohamed", vendor: "Palo Alto", certificate: "Security Operations Fundamentals", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Vmware", certificate: "vSphere 7.0", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Microsoft", certificate: "AZ-900", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Microsoft", certificate: "AZ-104", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Microsoft", certificate: "MS-900", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Microsoft", certificate: "MCSA", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Veeam", certificate: "Veeam Backup", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "Cisco", certificate: "CCNA V7.0", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "BeyondTrust", certificate: "BCIE-PS", expirationDate: "2027-06-30", expirationText: "2027-06-30", kind: "date" },
  { employee: "Mohamed Shafik", vendor: "Tenable", certificate: "Tenable Security Center Specialist", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mohamed Shafik", vendor: "Sangfor", certificate: "HCI Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Shafik", vendor: "BeyondTrust", certificate: "PRA", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Elkhresy", vendor: "Infoblox", certificate: "DDIP", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Ahmed Elkhresy", vendor: "Infoblox", certificate: "INA", expirationDate: "2026-07-05", expirationText: "2026-07-05", kind: "date" },
  { employee: "Ahmed Elkhresy", vendor: "Infoblox", certificate: "BloxOne DDI", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Ahmed Elkhresy", vendor: "Infoblox", certificate: "BloxOne ThreatDefence", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Ahmed Elkhresy", vendor: "Trillix", certificate: "nx", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Ahmed Elkhresy", vendor: "Infoblox", certificate: "NIOS DDI Expert", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Kaspersky", certificate: "Next EDR Foundation", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Kaspersky", certificate: "Kaspersky Next", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Kaspersky", certificate: "Kaspersky Next Presales", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "OpenText", certificate: "ArcSight ESM Administrator and Analyst", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Tenable", certificate: "Tenable Vulnerability Management Specialist On-Demand", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Trellix", certificate: "Trellix Endpoint Security | Technical Specialist", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Cisco Academy", certificate: "CyberOps Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Cisco Academy", certificate: "Network Security", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "RedHat", certificate: "Red Hat System Administration I (RH124)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "RedHat", certificate: "Red Hat System Administration II (RH134)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "SecurityOnion", certificate: "Security Onion Certified Professional (SOCP)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ramy Mohamed", vendor: "Invicti", certificate: "Technical Certified Dast", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Cisco", certificate: "CCNA Introduction to Networks", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Cisco", certificate: "CCNA Switching, Routing, and Wireless Essentials", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Cisco", certificate: "Enterprise Networking, Security, and Automation", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "RedHat", certificate: "Red Hat System Administration I", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Trellix", certificate: "Trellix Network Security | Technical Specialist (NX)", expirationDate: "2027-02-28", expirationText: "FEB, 2027", kind: "date" },
  { employee: "Mahmoud Rayan", vendor: "Trellix", certificate: "Trellix Endpoint Security | Technical Specialist (HX)", expirationDate: "2027-03-31", expirationText: "MAR, 2027", kind: "date" },
  { employee: "Mahmoud Rayan", vendor: "Fortinet", certificate: "Fortinet Certified Associate Cybersecurity", expirationDate: "2026-11-30", expirationText: "NOV, 2026", kind: "date" },
  { employee: "Mahmoud Rayan", vendor: "Trellix", certificate: "Trellix Email Security | Technical Specialist (EX)", expirationDate: "2027-06-30", expirationText: "JUN, 2027", kind: "date" },
  { employee: "Mahmoud Rayan", vendor: "Palo Alto", certificate: "NGFW-Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Kaspersky", certificate: "Next EDR Foundation", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "ProofPoint", certificate: "EMAIL PROTECTION LEVEL 1 FOR ANALYSTS AND ADMINISTRATORS", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mahmoud Rayan", vendor: "Trellix", certificate: "Endpoint Security for System Administrators", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "PT", certificate: "MaxPatrol VM engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Eltex", certificate: "Eltex MES Switches (advanced level) v.1", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Eltex", certificate: "Eltex MES Switches (basic level) v.1", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Fortinet", certificate: "NSE 4", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Palo Alto", certificate: "Prisma Cloud Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "PT", certificate: "Application Inspector Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Sophos", certificate: "Central Endpoint and Server Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Jamal", vendor: "Sophos", certificate: "Firewall Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mostafa Samy", vendor: "Trellix", certificate: "Trellix Service Provider HX", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mostafa Samy", vendor: "Trellix", certificate: "Trellix Service Provider NX", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mostafa Samy", vendor: "Trellix", certificate: "Trellix Service Provider ENS", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mostafa Samy", vendor: "Trellix", certificate: "DLP Endpoint Essentials", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mostafa Samy", vendor: "NETSCOUT", certificate: "Technical Certification – Security", expirationDate: "2027-12-25", expirationText: "2027-12-25", kind: "date" },
  { employee: "Mostafa Samy", vendor: "Tenable", certificate: "Partner Sales Engineer Vulnerability Management", expirationDate: "2027-01-25", expirationText: "2027-01-25", kind: "date" },
  { employee: "Mostafa Samy", vendor: "Tenable", certificate: "Sales Asscociate Vulnerability Exposure", expirationDate: "2027-01-25", expirationText: "2027-01-25", kind: "date" },
  { employee: "Mostafa Samy", vendor: "NETSCOUT", certificate: "Advanced Technical Certification – Service Assurance", expirationDate: "2027-04-26", expirationText: "2027-04-26", kind: "date" },
  { employee: "Mostafa Samy", vendor: "NETSCOUT", certificate: "Technical Certification for Service Provider - Assurance", expirationDate: "2027-04-26", expirationText: "2027-04-26", kind: "date" },
  { employee: "Mostafa Samy", vendor: "NETSCOUT", certificate: "Technical Certification – Assurance", expirationDate: "2027-04-26", expirationText: "2027-04-26", kind: "date" },
  { employee: "Mostafa Samy", vendor: "Acalvio", certificate: "ShadowPlex Deception Admin", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mostafa Samy", vendor: "Kaspersky", certificate: "Certified Professional: Kaspersky Next EDR Foundations", expirationDate: "2025-08-26", expirationText: "2025-08-26", kind: "date" },
  { employee: "Mostafa Samy", vendor: "Kaspersky", certificate: "Certified Professional: Kaspersky Next EDR Optimum", expirationDate: "2025-08-26", expirationText: "2025-08-26", kind: "date" },
  { employee: "Mostafa Samy", vendor: "Kaspersky", certificate: "Certified Instructor", expirationDate: null, expirationText: "N/A", kind: "no_expiration" },
  { employee: "Mohamed Ghanem", vendor: "Palo Alto", certificate: "NGFW-Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Ghanem", vendor: "Fortinet", certificate: "Certified Associate in Cybersecurity", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Ghanem", vendor: "Fortinet", certificate: "Certified Professional Secure Networking", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Ghanem", vendor: "Fortinet", certificate: "Certified Solution Specialist Secure Networking", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Mohamed Ghanem", vendor: "Cisco Academy", certificate: "Network Security", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Fares Abdeldaym", vendor: "Cisco Academy", certificate: "CCNA Routing and Switching", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Fares Abdeldaym", vendor: "Cisco Academy", certificate: "Cybersecurity Essentials", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Fares Abdeldaym", vendor: "Cisco Academy", certificate: "Introduction to Cybersecurity", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Fares Abdeldaym", vendor: "Palo Alto Academy", certificate: "Security Operations Fundamentals", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Email Security administrator", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Kaspersky", certificate: "Next EDR Foundation", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Forcepoint ONE Data Security Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Forcepoint DSPM Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Forcepoint DLP Administrator", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Data Security - Level 1", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forcepoint", certificate: "Data Security - Level 2", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Safetica", certificate: "Cerrtified Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Safetica", certificate: "Cerrtified Professional", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Safetica", certificate: "Cerrtified Sales Professional", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Cisco Academy", certificate: "Network Support and Security", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Forage", certificate: "Cybersecurity Analyst", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Cisco Academy", certificate: "Networking Basics", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Ahmed Ibrahim", vendor: "Kaspersky", certificate: "Next EDR Optimum", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Abdelrahman Musaa", vendor: "Palo Alto", certificate: "NGFW-Engineer", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Abdelrahman Musaa", vendor: "Cisco Academy", certificate: "CyberOps Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Abdelrahman Musaa", vendor: "Cisco Academy", certificate: "CCNA v7", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "OpenText", certificate: "ArcSight Administrator & Analyst", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "OpenText", certificate: "ArcSight ESM Advanced Analyst", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "OpenText", certificate: "ArcSight ESM Specialist", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "OpenText", certificate: "ArcSight ESM Technical Specialist", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Imperva", certificate: "Create Demand - DSF - Data Security", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Imperva", certificate: "Drive Sales - Data Security Fabric", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Red Hat Academy", certificate: "Red Hat System Administration I (RH124)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Red Hat Academy", certificate: "Red Hat System Administration II (RH134)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Red Hat Academy", certificate: "Red Hat System Administration III (RH254)", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Cisco Academy", certificate: "Network Security", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Omar Semeet", vendor: "Cisco Academy", certificate: "CyberOps Associate", expirationDate: null, expirationText: "", kind: "blank" },
  { employee: "Fares Abdeldaym", vendor: "Palo Alto", certificate: "Cloud Security Professional", expirationDate: "2028-11-14", expirationText: "2028-11-14", kind: "date" },
];

module.exports = { users, certificates };
